### PR TITLE
feat: add date placeholder logic

### PR DESCRIPTION
**Pull request by trey-wallis**
This update will add #10.

It also makes sure that the default file name used includes date placeholders. The default file name is now `{vaultName}-Backup-%Y_%m_%d-%H_%M_%S.zip`

### CODE REVIEW

**Comment by trey-wallis** [comment]
What are you using to style your code? It doesn't seem like there was any consistency between single quotes and double quotes.

I downloaded the `EditorConfig For VSCode` plugin from the VSCode plugin and used the `.editorconfig` file that came default from Obsidian. I opened the command palette and did "Format document"

**Comment by trey-wallis** [comment]
I am still fixing an error with the merge conflict

**Comment by trey-wallis** [comment]
The code works on my end. I'm open to receive any feedback :)

**Comment by cgcel** [comment]
Thank you for your job!

**Pull request merged**
